### ISSUE TITLE
signum is specified as Int, needs to be number-specific

### ISSUE THREAD

**Issue by soc** [non/spire#117]
`Number` currently defines `signum` with a result type of `Int`.

This is wrong, and will break as soon as you put almost anything non-`Int` into it.
For instance, what's the result of `Double.NaN.signum`? Not `0`, for sure.
Another example is `Complex`: The result of `complex.signum` is another `Complex` value, not an `Int`.

`signum` should have a result type of type `T` where `T` is the actual numeric type.

**Comment by denisrosset** [comment]
Closing this due to a long period of inactivity. Please consider opening a new issue or reopening this PR to restart discussion. We're very sorry for the possible inconvenience. See #674
