### ISSUE TITLE
Investigate removal of some NormedVectorSpace instances

### ISSUE THREAD

**Issue by tixxit** [non/spire#147]
While working on the serializable stuff, I noticed that there are some NormedVectorSpace classes that aren't used (AFAICT). This is because they just use `InnerProductSpace#normed` (which just requires `NRoot[F]`) instead of actually using the trait that was implemented. If this is the case, we can just remove these. Namely, I'm looking at the `Seq` and `Array` ones.

**Comment by denisrosset** [comment]
Closing this due to a long period of inactivity. Please consider opening a new issue or reopening this PR to restart discussion. We're very sorry for the possible inconvenience. See #674
