### ISSUE TITLE
Systematic recompilations of some sources

### ISSUE THREAD

**Issue by luc-j-bourhis** [non/spire#156]
Every time core/test or core/compile is fired, sbt reports that 3 Scala sources from core/target/scala-2.10/classes/... and then 1 class source from the same place (the … is what sbt prints out: I don't know the exact path) are compiled.

d_m said on irc that he thinks this is related to codegen, i.e. some files are always "dirty". This is annoying on a slow machine as those recompilations can take a few seconds.

**Comment by denisrosset** [comment]
Closing for now. We are modularizing Spire, which should help a bit.
