### ISSUE TITLE
Commutativity problems

### ISSUE THREAD

**Issue by non** [non/spire#198]
Right now, using types for commutativity is a bit awkward. There are a few problems:
- It's easy to forget to provide types like `CRing` in addition to `Ring`
- In cases where both types could be provided with different evidence, you have to use the "low-priority" implicit pattern to avoid ambiguity.
- In cases where you can accept `Ring` or `CRing` but would prefer the latter for optimization reasons, it's hard to do this. There has been some talk about using some kind of `Fallback` type class to help fix this.

I'm not sure what the best approach is. One option is to stop differentiation `CRing` and `Ring`, but instead use a type witness like `CommutativeMult[A]` or something. Another approach is to leave things alone but just make sure commutativity is being supported everywhere it might be needed (e.g. add `CSemiring` and `CRng`). A third option is to figure out a more radical plan.

**Comment by denisrosset** [comment]
We added the `CSemiring` and `CRng` types, so going with the second option.
