### ISSUE TITLE
Generalize, expand, and rationalize literal syntax macros

### ISSUE THREAD

**Issue by non** [non/spire#202]
Right now we have some fancy syntax macros like `r"3/7"` and `poly"x^2 + 7"`.

But we will run out of letters if we keep adding these for all the types we want. And some types might benefit from being parameterized on other types (e.g. `Polynomial`, `Complex`, or `Interval`).

We should figure out a general way to let users specify nice, compact literals for all of our types, while trying to control the "syntax explosion" of a million possible string prefixes.

We may also want to consider using method syntax instead of string interpolation syntax in some cases, e.g. `poly("x^2 + 7")`.

**Comment by denisrosset** [comment]
Closing due to being part of a larger discussion
