### ISSUE TITLE
More work on non/algebra

### ISSUE THREAD

**Issue by non** [non/spire#204]
The http://github.com/non/algebra project is attempting unify Algebird, Spire, and possibly other libraries. We should try to push that through, since it will make interop a lot easier.

**Comment by rklaehn** [comment]
Here is a branch for algebra integration that merges with master: https://github.com/rklaehn/spire/tree/topic/algebra-integration

What about spire.std? Should default instances also aliased to algebra?

**Comment by denisrosset** [comment]
Good job @non!
