### ISSUE TITLE
Breeze integration

### ISSUE THREAD

**Issue by non** [non/spire#218]
It would be great to add Spire as a Breeze dependency, so they could benefit from our type classes and to increase ease of interop between the two projects.

There's a GSOC project with this same goal: http://www.scala-lang.org/gsoc/2014.html

At this point I think Spire has the type classes Breeze needs. The task involves figuring out if we do, and then submitting a PR to Breeze that makes the change.

**Comment by suhailshergill** [comment]
@non any updates on this?

**Comment by denisrosset** [comment]
Closing this due to a long period of inactivity. Please consider opening a new issue or reopening this PR to restart discussion. We're very sorry for the possible inconvenience. See #674
