### ISSUE TITLE
Consider more exotic algebras

### ISSUE THREAD

**Issue by non** [non/spire#224]
It might be nice to consider more exotic algebras and categories. Lie and Clifford algebras, groupoids, lattices, etc. I'm not sure any of these are necessary but if someone is excited to work on them and has a use case, it would be interesting to see how well they integrate into `spire.algebra`.

**Comment by denisrosset** [comment]
Closing this due to a long period of inactivity. Please consider opening a new issue or reopening this PR to restart discussion. We're very sorry for the possible inconvenience. See #674
