### ISSUE TITLE
Work on fleshing out and profiling soc's BigInt type

### ISSUE THREAD

**Issue by non** [non/spire#226]
Simon Ochsenreither has done significant work on implementing a from-scratch BigInt type, using some patches from Tim Buktu and other Java numerical folks. This task is about fleshing out those types, benchmarking them (to make sure they represent an improvement over `java.math.BigInteger`) and then plugging them into Spire.

This obviates the need for `BigInt` (which is obviously a wrapper around `BigInteger`), and might also obviate the need for `SafeLong` if we can build the same kind of fast-path for `Long` values into it.

**Comment by denisrosset** [comment]
Regrouped.

**Comment by armanbilge** [comment]
I think some of these ideas found their way into https://github.com/scala/scala/pull/9628.
