### ISSUE TITLE
Document new PartialOrder[A] type

### ISSUE THREAD

**Issue by non** [non/spire#282]
At a minimum we need to update the [README.](README.md) and the [GUDIE.md](GUIDE.md).

A good start is to look for where we describe `Order[A]` and add something afterwards about `PartialOrder[A]` as well. (I would describe order first since it is probably more familiar to folks.)

**Comment by denisrosset** [comment]
Closing this due to a long period of inactivity. Please consider opening a new issue or reopening this PR to restart discussion. We're very sorry for the possible inconvenience. See #674
