### ISSUE TITLE
Spire style guide

### ISSUE THREAD

**Issue by denisrosset** [non/spire#315]
Spire/Scalaz/... are pioneering the use of typeclasses, however it is not immediately clear where to put the different parts of the typeclass and its syntax, and how to name them.

I would propose to create a small guide to help people find their way around the source code. Any ideas on the guidelines ?

This would also be helpful for libraries using the Spire typeclasses.
- the package structure is very well described in the [guide](https://github.com/non/spire/blob/master/GUIDE.md)
- when `math.X` is an object, there is a trait `XInstances` with the corresponding typeclass instances, and the companion object `math.X` extends `XInstances`,
- each type class instance is written in a separate trait. For "algebraic" classes (to be defined), a master trait `XAlgebra` collects all the pieces,
- these traits are instantiated in the `XInstances` trait using `implicit final val`, with the val name being the type name, thus emulating a singleton object.

(this variant is used by `UByte` and friends)
- or there is an implicit object in the `XInstances` trait collecting all the algebraic typeclasses.

(this variant is used by `SafeLong`)

This should be written along an explanation of the reasoning behind the structure.

Note: as the core maintainers form a small team, I don't think the project needs a strict guide, but it would be helpful for newcomers, as the typeclass pattern is not yet fully documented.

**Comment by armanbilge** [comment]
I think this issue is pretty stale. Typeclasses are well established now and we can follow best practices from Cats, Cats Effect etc. Furthermore Scala 3 brings many improvements to this style of programming, so a Scala 2 focused style guide will have limited lifetime.
