### ISSUE TITLE
Consider splitting algebra traits into interface + impl traits

### ISSUE THREAD

**Issue by non** [non/spire#317]
As per this twitter conversation with @paulp:

https://twitter.com/extempore2/status/530087467282472960
https://twitter.com/extempore2/status/530087869306515456

I think this is doable -- we mostly put implementations in algebra traits to allow users to extend them using a minimal number of methods, but we can still achieve this via Impl traits.

**Comment by denisrosset** [comment]
Closing for now as it is quite old.
