### ISSUE TITLE
ScalaJS support

### ISSUE THREAD

**Issue by antonkulaga** [non/spire#321]
It would be great to see spire crosscompiled to ScalaJS

**Comment by antonkulaga** [comment]
>Once these classes are implemented for ScalaJS, the cross-compilation should be only a matter of ironing the small implementation differences between Javascript and the JVM.

Bigdecimals were implemented by @InTheNow and are available in the latest scalajs release

**Comment by denisrosset** [comment]
We support Scala.js now.
