### ISSUE TITLE
Rational.equals very slow for LongRational

### ISSUE THREAD

**Issue by rklaehn** [non/spire#366]
Comparing two LongRational using equals/==/=== is much slower than it has to be. 

Here is a little benchmark that compares == to a "fastEquals" method

    Rational primitive operations benchmark Integer 12345 67890
    Benchmark for a == b (20 calls in 311.3 ms)
      Time:    58.94 ns   95% CI 58.29 ns - 59.58 ns   (n=20)
      Garbage: 0.1907 ns   (n=1 sweeps measured)
    Benchmark for a fastEquals b (20 calls in 495.0 ms)
      Time:    5.889 ns   95% CI 5.852 ns - 5.925 ns   (n=20)

And here is the "fastEquals" method:

    def fastEquals(a:Rational, b:Rational) = (a, b) match {
      case (LongRational(an,ad), LongRational(bn, bd)) ⇒
        an == bn && ad == bd
      case _ ⇒
        a == b
    }

I think the current equals method is less than optimal since it uses RationalLike

    override def equals(that: Any): Boolean = that match {
      case that: Real => this == that.toRational
      case that: Algebraic => that == this
      case that: RationalLike => num == that.num && den == that.den // <= this is boxing
      ...
    }

Overriding equals for LongRational to check rhs for LongRational should fix this.

**Comment by tixxit** [comment]
Sounds like an easy win. :+1:
