### ISSUE TITLE
Investigate using Checked.tryOrElse to speed up rational binary operations

### ISSUE THREAD

**Issue by rklaehn** [non/spire#377]
This is not as clear-cut as in #370 , but there nevertheless might be some benefit in trying to do everything with longs and only switching to SafeLong when there is an overflow. 

E.g. in LongRational *:

```scala
  case r: LongRationals.LongRational =>
    val a = spire.math.gcd(n, r.d)
    val b = spire.math.gcd(d, r.n)
    Checked.tryOrElse {
      // if there is no overflow, we know that the result is a LongRational. We also don't have to use apply
      // since we know that there is no common fraction (?)
      LongRationals.build((n / a) * (r.n / b), (d / b) * (r.d / a))
    } {
      Rational(SafeLong(n / a) * (r.n / b), SafeLong(d / b) * (r.d / a))
    }
```

The benefit will not be as large as in compare, since the gcds have to be calculated in any case. But when looking at some code using rationals in yourkit, I see some significant portion of the time being spent in java.lang.Number.init, which gets called indirectly by LongRationals.$LongRational.$times.

The question is for which rationals the rational number type should be optimized. In my application, I assume that the very vast majority of my rationals will comfortably fit into a LongRational, so this part of the code is most important to me.

**Comment by non** [comment]
We've merged two PRs for this. @rklaehn do you think we should keep this issue open or close it?

**Comment by rklaehn** [comment]
No, I think this can be closed. The other rational issue I opened can also be closed.

Fixed by
