### ISSUE TITLE
Bug in Rational nroot

### ISSUE THREAD

**Issue by rklaehn** [non/spire#392]
Rational.nroot or pow hangs for some very simple test cases. E.g. 

```scala
implicit val ac = ApproximationContext(Rational(1L, 100000000000000000L) // I can also set this to 1, it does not seem to matter
Rational(3) pow Rational(2) // hangs
```

The cause seems to be that Rational.nroot(Long,Int) does not terminate for some simple inputs. It probably just misses an additional cutoff.

```scala
Rational.nroot(9,1) // hangs
```

**Comment by tixxit** [comment]
I say we get rid of `nroot` (and `ApproximationContext`) on `Rational`. Both `Algebraic` and `Real` can wrap a `Rational` and provide an exact `nroot`.

**Comment by rklaehn** [comment]
Sounds good.
