### ISSUE TITLE
Opt boxes in scala 2.10

### ISSUE THREAD

**Issue by woparry** [non/spire#401]
The scala 2.10 version of Opt inherits from a custom OptVersions.Base trait instead of AnyVal, so it boxes. As far as I can tell the whole purpose of Opt rather than Option is to avoid boxing, so I consider this a bug.

Test case:

import spire.util.Opt

class Test {
  def test(): Opt[String] = {
    val t = Opt("test")
    t.map(_ + "ing")
  }
}

In 2.10:

public spire.util.Opt<java.lang.String> test();
    Code:
       0: getstatic     #16                 // Field spire/util/Opt$.MODULE$:Lspire/util/Opt$;
       3: ldc           #17                 // String test
       5: invokevirtual #21                 // Method spire/util/Opt$.apply:(Ljava/lang/Object;)Lspire/util/Opt;
       8: astore_1  
       9: aload_1  
      10: new           #23                 // class spire/util/Test$$anonfun$test$1
      13: dup  
      14: aload_0  
      15: invokespecial #27                 // Method spire/util/Test$$anonfun$test$1."<init>":(Lspire/util/Test;)V
      18: invokevirtual #33                 // Method spire/util/Opt.map:(Lscala/Function1;)Lspire/util/Opt;
      21: areturn 

In 2.11:

 public java.lang.String test();
    Code:
       0: getstatic     #16                 // Field spire/util/Opt$.MODULE$:Lspire/util/Opt$;
       3: ldc           #17                 // String test
       5: invokevirtual #21                 // Method spire/util/Opt$.apply:(Ljava/lang/Object;)Ljava/lang/Object;
       8: checkcast     #23                 // class java/lang/String
      11: astore_1  
      12: getstatic     #16                 // Field spire/util/Opt$.MODULE$:Lspire/util/Opt$;
      15: aload_1  
      16: new           #25                 // class spire/util/Test$$anonfun$test$1
      19: dup  
      20: aload_0  
      21: invokespecial #29                 // Method spire/util/Test$$anonfun$test$1."<init>":(Lspire/util/Test;)V
      24: invokevirtual #33                 // Method spire/util/Opt$.map$extension:(Ljava/lang/Object;Lscala/Function1;)Ljava/lang/Object;
      27: checkcast     #23                 // class java/lang/String
      30: areturn

Note:

The return type from Opt$.apply:
  Lspire/util/Opy; in 2.10
  Ljava/lang/Object in 2.11 (and then cast to String)

The return type from test():
  spire.util.Opt in 2.10
  java.lang.String in 2.11

Clearly the 2.10 code is generating an actual Opt object to wrap around our string.

I propose that in 2.10 we should get rid of OptVersion.Base and just use AnyVal. In that case:

 public java.lang.String test();
    Code:
       0: getstatic     #16                 // Field spire/util/Opt$.MODULE$:Lspire/util/Opt$;
       3: ldc           #17                 // String test
       5: invokevirtual #21                 // Method spire/util/Opt$.apply:(Ljava/lang/Object;)Ljava/lang/Object;
       8: checkcast     #23                 // class java/lang/String
      11: astore_1  
      12: getstatic     #16                 // Field spire/util/Opt$.MODULE$:Lspire/util/Opt$;
      15: aload_1  
      16: new           #25                 // class spire/util/Test$$anonfun$test$1
      19: dup  
      20: aload_0  
      21: invokespecial #29                 // Method spire/util/Test$$anonfun$test$1."<init>":(Lspire/util/Test;)V
      24: invokevirtual #33                 // Method spire/util/Opt$.map$extension:(Ljava/lang/Object;Lscala/Function1;)Ljava/lang/Object;
      27: checkcast     #23                 // class java/lang/String
      30: areturn

The code is very similar to the 2.11 code. The return types are identical.

**Comment by denisrosset** [comment]
Hi @woparry ,

this is on purpose, and this is why a different implementation is made for 2.10 and 2.11. There is a bug in the Scala 2.10 compiler that prevents the implementation of `Opt` containing an `Any` object.

You are welcome to try making `Opt` not boxing on 2.10 and send a PR.

**Comment by denisrosset** [comment]
Let's keep this issue open, I need to add documentation to `Opt` highlighting this particular implementation choice.

**Comment by woparry** [comment]
That would be great!

Is the compiler issue you're referring to https://issues.scala-lang.org/browse/SI-6385?

As far as I can swapping in AnyVal works on Opt by itself (both Opt(1) and Opt(1.asInstanceOf[Any]) give sensible output on the console at least). Compiling it with the rest of Spire gives a bunch of errors like 

/Users/oparry/workspace/spire/core/src/main/scala/spire/algebra/partial/Semigroupoid.scala:26: bridge generated for member method partialOp: (x: A, y: A)spire.util.Opt[A] in anonymous class $anon
[error] which overrides method partialOp: (x: A, y: A)spire.util.Opt[A] in trait Semigroupoid
[error] clashes with definition of the member itself;
[error] both have erased type (x: Object, y: Object)Object
[error]       def partialOp(x: A, y: A): Opt[A] = Opt(semigroup.op(x, y))

which looks like the compiler is not remembering the type information long enough.

**Comment by woparry** [comment]
Since it looks like the fix in 2.11 is to rename the unboxed method since it can't ever be called (from an anonymous class), I wonder if we could apply a similar fix via a macro. I'll investigate that line.

**Comment by denisrosset** [comment]
How deep did you investigate this, @woparry ? Is it hopeless ?

**Comment by woparry** [comment]
I didn't investigate too deeply; it's not hopeless but we moved to 2.11 so I stopped caring, sorry. Feel free to close.

**Comment by denisrosset** [comment]
We are dropping 2.10.
