### ISSUE TITLE
Add === methods to all data types

### ISSUE THREAD

**Issue by non** [non/spire#423]
Right now we rely on universal equality even when we know the specific type of the RHS. Instead we should give our data types concrete `===` methods.

For example, `Rational` would support `def ===(rhs: Rational): Boolean`, and `Complex[A]` would support `def ===(rhs: Complex[A]): Boolean`.

**Comment by kevinmeredith** [comment]
Hi @non. 

From a Haskell point-of-view, that means adding `deriving Eq` to each of the data types? To do that, shapeless can be used?

Miles's [talk](https://twitter.com/milessabin/status/586806370953011200) from ScalaDays shows how to do this, as I incompletely understand.

Would the [Equal](http://eed3si9n.com/learning-scalaz/Equal.html) type-class from scalaz be used here? I don't know how much shapeless and scalaz work together.

Thank you.

**Comment by non** [comment]
Hi @kevinmeredith,

So there are a few things going on here, that are maybe not clear due to the way I wrote the bug.

This issue is about providing the `===` method directly, instead of relying on type classes to do it. This is mostly about documenting that the types have this capability directly. You'll notice that these types also provide methods like `+`, `*`, and so on, instead of relying solely on type classes to provide that functionality. This is partially for convenience reasons and partially for performance.

It is definitely possible to derive type class instances with Shapeless in some cases. Currently, these types all have manually-written instances, and I'm not sure that it would be worth it to try to get the same implementations automatically.

Spire uses its own type class for equality (`Eq`), not the one from Scalaz. There are several reasons for this but the primary one is that Spire's type classes are specialized for primitive types.

**Comment by kevinmeredith** [comment]
Would you consider this list to be exhaustive - https://github.com/non/spire/issues/405#issuecomment-83022039?

If so, what's the right way to implement `===` for each type:

```... with Equal[Algebraic] { 
        override def ===(x: Algebraic) = this == x
```

Is the motivation to use `===` to discourage the usage of `==`?

**Comment by non** [comment]
Currently a lot of our `equals` methods look like this:

```scala
def equals(that: Any): Boolean =
  that match {
    case x: MyThing => /* equality code */
    case _ => false
  }
```

I'm suggesting we change this to:

```scala
def ===(that: MyThing): Boolean = /* equality code */

def equals(that: Any): Boolean =
  that match {
    case x: MyThing => this === x
    case _ => false
  }
```

Does that make sense?

**Comment by kevinmeredith** [comment]
Yes, thanks for clearing up my confusion, Erik.

So, re-factoring `Algebraic`'s `equals` would look like:

```
  override def equals(that: Any) = that match {
    case (that: Algebraic) => this.compare(that) == 0
     ...  
  }

  def ===(that: Algebraic): Boolean = 
     this.compare(that) == 0
```

But, that made me think about your mention of `Eq`. Given the fact that [Eq](https://github.com/non/spire/blob/master/core/src/main/scala/spire/algebra/Eq.scala#L10-L22), has 3 methods, would you expect `===` to be added as an `EqOps`, which ultimately calls `eqv` from `Eq#eqv`?

With the `EqOps`, I was thinking of this [article](http://typelevel.org/blog/2013/07/07/generic-numeric-programming.html)'s usage of `AddOps`.

Thanks

**Comment by non** [comment]
Yes, we already have those operators. I'll try to catalogue the full complement of stuff going here:

1. `Algebraic#===` method for comparing two `Algebraic` instances
2. `Algebraic#==` method for comparing an `Algebraic` to anything
3. `Eq[A]#eqv` generic type class method for comparing two `A` values
4. `Eq[Algebraic]#eqv` type class instance for comparing two `Algebraic` values, should probably use (1).
5. `EqOps[A]#===` operator syntax for `Eq[A]`, will call (2) generically.

If we are dealing with `Algebraic` values we won't need to use (3), (4), or (5). However in generic contexts where we are dealing with `A` and have `Eq[A]` then we willy rely on (5) to support direct syntax, which will dispatch to (4) (which is a specific instance of (3)).

Does this make sense? I am trying to explain the underlying complexity of the generic versus specific encodings while staying relatively high-level.

**Comment by kevinmeredith** [comment]
Thanks for the clear explanation.

I think that I'm good to implement that. I'll issue a PR and ask a particular question for Algebraic if I run into any. And then I'll do the rest of the types per this issue.

**Comment by non** [comment]
Sounds great! Thanks for your energy and questions.

**Comment by kevinmeredith** [comment]
[ULong#==](https://github.com/non/spire/blob/master/core/src/main/scala/spire/math/ULong.scala#L67) is already defined.

`final def == (that: ULong): Boolean = this.signed == that.signed`

Would you expect that `===` would be added, or would replace `==`?

**Comment by denisrosset** [comment]
Regrouped!
