### ISSUE TITLE
Law checks should check consistency of overridable methods with abstract methods

### ISSUE THREAD

**Issue by rklaehn** [non/spire#448]
A law check should not just check all abstract methods of a type class, but also non-abstract overridable methods for consistency with the abstract methods.

Currently, this is not the case for e.g. LogicLaws. Here is an obviously broken implementation of Bool[Bool] that nevertheless passes the LogicLaws checks.

``` scala
import org.scalacheck.{Arbitrary, Properties}
import org.typelevel.discipline.Laws
import spire.algebra.{Eq, Bool}
import spire.laws.LogicLaws

object LogicLawTestCheck extends Properties("LogicLawCheck") {

  def addProperties(name:String, ruleSet: Laws#RuleSet) {
    for ((id, prop) ← ruleSet.all.properties)
      property(name + "." + id) = prop
  }

  val brokenBoolAlgebra = new Bool[Boolean] with Eq[Boolean] {
    def and(a: Boolean, b: Boolean) = a & b
    def or(a: Boolean, b: Boolean) = a | b
    def complement(a: Boolean) = !a
    def one = true
    def zero = false
    def eqv(x: Boolean, y: Boolean) = x == y
    override def xor(a: Boolean, b: Boolean) = false // wrong!
    override def nand(a: Boolean, b: Boolean) = false // wrong!
    override def nor(a: Boolean, b: Boolean) = false // wrong!
    override def nxor(a: Boolean, b: Boolean) = false // wrong!
  }

  addProperties("TestBoolean", LogicLaws(brokenBoolAlgebra, Arbitrary.arbBool).bool(brokenBoolAlgebra))
}
```

**Comment by rklaehn** [comment]
I just checked RingLaws. It seems that isOne, isZero, sumOption, prodOption and pow are not being called.

Also, does anybody see a problem with making prodn and sumn final?

**Comment by rklaehn** [comment]
I tried adding a minimal test for pow that just checks that x pow 1 == x, x pow 2 == x * x and x pow 3 == x * x * x. Using an arbitrary positive int would take way too long. It fails for something as simple as IntAlgebra: x pow 2 =!= x * x when there is an overflow. E.g.
``` 
x = 1632673887
x * x = -1646861503
x pow 2 = 2147483647
```

Is this a bug? I would say so.

**Comment by non** [comment]
Yes!

I've fixed this same bug in other places -- it comes from using `scala.math.pow` (which operates on `Double`) for powers of `Int` or `Long` values and converting back at the end. Let's fix it!

`spire.math.pow` should work correctly for `Long` values, so we should be able to use that instead.

**Comment by rklaehn** [comment]
This seems to fix it.
```
-  override def pow(a:Int, b:Int): Int = Math.pow(a, b).toInt
+  override def pow(a:Int, b:Int): Int = spire.math.pow(a, b).toInt
```

You think just checking exponents 1,2 and 3 is enough? Using an arbitrary int will be too slow for some types.

**Comment by non** [comment]
Yes, I agree. We can just check that:
 * x^1 = x
 * x^2 = x * x
 * x^3 = x^2 * x = x * x * x

**Comment by rklaehn** [comment]
OK. I now got
```
    "pow" → forAll((x: A) =>
      ((x pow 1) === x) && ((x pow 2) === x * x) && ((x pow 3) === x * x * x)
    )
```

What about sumOption and prodOption? Just test it with collections of size 0, 1, 2, 3 of a single arbitrary value?

**Comment by non** [comment]
Yeah, that seems fine. Thanks again for working on this!
