### ISSUE TITLE
Adding Cosets?

### ISSUE THREAD

**Issue by kevinmeredith** [non/spire#473]
I know little about [cosets](http://math.stackexchange.com/questions/1366946/find-the-cosets-of-subgroup-langle-3-rangle-of-mathbbz/1366948?noredirect=1#comment2782107_1366948), but are they worthwhile to add to non/spire?

I'm studying them now, but I'd be interested in adding them if it's worthwhile and OK with the spire team.

**Comment by denisrosset** [comment]
Hi @kevinmeredith,

I'm building a library for computational group theory in Scala, based on Spire: https://github.com/denisrosset/alasc , containing a rough implementation of cosets.

Of course, the implementation there is pretty much tied to my finite group objects.

What are you thinking of especially (in terms of algebraic structures, laws) ?

**Comment by kevinmeredith** [comment]
Hi @denisrosset -

I did not have any thoughts with respect to the algebraic structures and laws.

I'm just reading and working through some of the exercises from "A Book of Abstract Algebra." Running into the topic of Cosets sparked my interest, namely with respect to this library.

Once I complete more exercises from that book on Cosets, I'll take a look at your library.

Thanks for pointing me to it! 

I'm going to close this issue given your related work (that uses non/spire).
