### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by rklaehn** [non/spire#481]
Currently our code coverage is nothing to write home about. We should try to improve it.

If a section of code should not be considered for coverage testing, it can be excluded using

```
// $COVERAGE-OFF$
...
// $COVERAGE-ON$

But of course that should be only done as a last resort. I have found that providing coverage even for seemingly trivial code can expose bugs.
```

**Comment by maciejjaskowski** [comment]
I'd have some time in the following weeks to help with that. Would you be interested in such contribution ?

**Comment by rklaehn** [comment]
@maciejjaskowski sorry about not answering sooner. We would *definitely* be interested in such contributions. Every little bit helps.

**Comment by denisrosset** [comment]
It is part of the roadmap during modularization.
