### ISSUE TITLE
Bug in Rational.gcd

### ISSUE THREAD

**Issue by denisrosset** [non/spire#488]
There is a small bug in LongRational.gcd when the right hand side is a BigRational and the left hand side is zero:
```
scala> Rational.zero gcd Rational(BigInt(2)**100)
java.lang.ArithmeticException: BigInteger divide by zero
  at java.math.MutableBigInteger.divideKnuth(MutableBigInteger.java:1179)
  at java.math.MutableBigInteger.divideKnuth(MutableBigInteger.java:1163)
  at java.math.BigInteger.remainderKnuth(BigInteger.java:2124)
  at java.math.BigInteger.remainder(BigInteger.java:2112)
  at scala.math.BigInt.$percent(BigInt.scala:213)
  at spire.math.LongRationals$LongRational.gcd(Rational.scala:653)
  at spire.math.BigRationals$BigRational.gcd(Rational.scala:834)
  ... 43 elided
```

**Comment by non** [comment]
I wonder if this bug is still present in https://github.com/non/spire/pull/487.

**Comment by rklaehn** [comment]
I just moved stuff around. So I would be surprised if it was fixed.

Erik Osheim <notifications@github.com> schrieb am Do., 6. Aug. 2015 02:38:

**Comment by rklaehn** [comment]
So it seems that the expected behavior is to just return the abs of the other. From spire.math.gcd:
```
  final def gcd(_x: Long, _y: Long): Long = {
    if (_x == 0L) return Math.abs(_y)
    if (_x == 1L) return 1L
    if (_y == 0L) return Math.abs(_x)
    if (_y == 1L) return 1L
```
@denisrosset So I guess we should just do the same for Rational.gcd? Would you mind if I do this directly on my #487 branch that has a handy Rational.isOne method?

**Comment by denisrosset** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Greatest_common_divisor):

> gcd(a, 0) = |a|, for a ≠ 0, since any number is a divisor of 0, and the greatest divisor of a is |a|. This is usually used as the base case in the Euclidean algorithm.

> It is sometimes useful to define gcd(0, 0) = 0 and lcm(0, 0) = 0 because then the natural numbers become a complete distributive lattice with gcd as meet and lcm as join operation. This extension of the definition is also compatible with the generalization for commutative rings given below.

so all good.
