### ISSUE TITLE
More principled approach to cooperative equality

### ISSUE THREAD

**Issue by rklaehn** [non/spire#508]
Cooperative equality in spire (and in other libraries such as scala collections) can be improved. Types that are completely unrelated depend on each other because they try to participate in mutual cooperative equality. So from a code cleanliness POV my first desire would be to rip it all out. In the example below, why does Algebraic even have to know that Quaternion exists, and vice versa?

Exhibit A: Algebraic.equals:

``` scala
  override def equals(that: Any): Boolean = that match {
    case (that: Algebraic) => this === that
    case (that: Real) => this.toReal == that
    case (that: Number) => this.compare(Algebraic(that.toBigDecimal)) == 0
    case (that: Rational) => this.compare(Algebraic(that)) == 0
    case (that: BigInt) => isWhole && toBigInt == that
    case (that: Natural) => isWhole && signum >= 0 && that == toBigInt
    case (that: SafeLong) => isWhole && that == this
    case (that: Complex[_]) => that == this
    case (that: Quaternion[_]) => that == this
    case (that: BigDecimal) => try {
      toBigDecimal(that.mc) == that
    } catch {
      case ae: ArithmeticException => false
    }
    case _ => unifiedPrimitiveEquals(that)
  }
```

But on the other hand people have come to expect cooperative equality. And it sure is useful to be able to compare e.g. a Rational with an integer etc.

So we need a better approach. As a minimum, it needs to be external to the types themselves. That excludes using ==. Let's just forget about ==/equals.

I think there should be a distinction between normal equality (that requires that lhs and rhs are of the same type), and cooperative equality that is more relaxed. So different operators. === for strict equality and =~= for cooperative equality? 

=== should only work if both sides are the same type and not apply any implicit conversions. Note that this is not the case for a method.

=~= should work if there exists an implicit conversion from the type of lhs to the type of rhs or vice versa, and there exists an Eq instance. It should be possible to provide explicit cooperative equality for a type pair to increase efficiency. E.g. comparing a Rational to an Int without first converting the Int to Rational.

**Comment by rklaehn** [comment]
Here are some experiments with a typeclass for cooperative equality.
```
package eqs

object Bla extends App {

  implicit class EqOps[T](val lhs: T) extends AnyVal {
    def ===[U](rhs: U)(implicit ev: Eq[T], x: T =:= U) = ev.eqv(lhs, rhs.asInstanceOf[T])
  }

  trait Eq[T] {
    def eqv(a: T, b: T): Boolean
  }

  implicit class CEqOps[T](val lhs: T) extends AnyVal {
    def =~=[U](rhs: U)(implicit ev: CEq[T, U]): Boolean = ev.same(lhs, rhs)
  }

  trait CEq[A, B] extends Any {
    def same(a: A, b: B): Boolean
  }

  implicit def flip[T, U](implicit x: CEq[U, T]): CEq[T, U] = new CEq[T, U] {
    override def same(a: T, b: U): Boolean = x.same(b, a)
  }

  implicit def ceq1[T, U](implicit e: Eq[T], f: U => T): CEq[T, U] = new CEq[T, U] {
    def same(a: T, b: U) = e.eqv(a, f(b))
  }

  implicit def ceq2[T, U](implicit f: T ⇒ U, e: Eq[U]): CEq[T, U] = new CEq[T, U] {
    def same(a: T, b: U) = e.eqv(f(a), b)
  }

  implicit object IntEq extends Eq[Int] {
    override def eqv(a: Int, b: Int): Boolean = a == b
  }

  implicit object LongEq extends Eq[Long] {
    override def eqv(a: Long, b: Long): Boolean = a == b
  }

  case class Foo(x: Int)

  case class Bar(x: Int)

  case class Baz(x: Int)

  object Bar {
    implicit def fromFoo(foo: Foo): Bar = Bar(foo.x)
  }

  implicit object BarEq extends Eq[Bar] {
    override def eqv(a: Bar, b: Bar): Boolean = a.x == b.x
  }

  implicit object FooBazEq extends CEq[Foo, Baz] {
    override def same(a: Foo, b: Baz): Boolean = a.x == b.x
  }

  println(1 === 1) // uses IntEq
  // println(1 === 1L) // does not compile
  println(1 =~= 1L) // uses LongEq and Int => Long upcast of first arg via ceq2
  println(1L =~= 1) // uses LongEq and Int => Long upcast of second arg via ceq1
  println(Foo(1) =~= Bar(1)) // uses Foo => Bar upcast in Bar companion
  println(Bar(1) =~= Foo(1)) // uses Foo => Bar upcast in Bar companion
  println(Foo(1) =~= Baz(1)) // uses direct FooBazEq
  println(Baz(1) =~= Foo(1)) // uses FooBazEq and flip
}
```

**Comment by rklaehn** [comment]
@non @tixxit what do you think? I don't know if this is the right approach, but we definitely have to do *something* to untangle the maze of the equals methods used for cooperative equality.

**Comment by non** [comment]
So, I do like the idea of introducing `=~=` in some form. I'm not sure if we should power it with implicit conversions, or some kind of general conversion type class. I'm a bit too tired to sketch it out now unfortunately.

**Comment by rklaehn** [comment]
No problem. It will take some time to get this right. Also, spire might not be the best place for it.

What would be the best unicode alias? There is [≈](http://www.fileformat.info/info/unicode/char/2248/index.htm) and [≅](http://www.fileformat.info/info/unicode/char/2245/index.htm). The latter is called approximately equal to, so it might best be reserved for things like fuzzy comparisons of e.g. doubles.

Thinking about this some more, *I think we should not have === as a method*. === as a method is fundamentally non-symmetric (will apply implicit conversions to rhs, but not to lhs). But equality is meant to be symmetric. Also the namespace is already polluted with enough broken equality methods (==, !=), so let's not add more... :-/

I really like having === only working if lhs and rhs are of the same type, so 1L === 1 or 1 === 1.0 should not compile. But the question is if it is possible to get the above approach using =:= fast enough.

**Comment by rklaehn** [comment]
By the way: I think this is really important. If there is a need for [commercial tools](http://www.artima.com/shop/supersafe) to deal with the inadequacies of your built-in equality mechanism, there is clearly a need for a better mechanism.

**Comment by rklaehn** [comment]
I did some benchmarks. One surprising (to me) unrelated takeaway: there is a measurable difference between == and equals for Rational and even for java objects like Strings.

Cooperative equality does not seem to add too much overhead (see cooperativeEq and cooperativeEqInt). However, there seems to be something seriously wrong with Rational(1234) == 1234. No idea why it is so slow. Probably related to something inherited from scala like ScalaNumericConversions.

```
[info] Benchmark                                                Mode  Samples   Score  Score error  Units
[info] s.b.j.CooperativeEqBenchmarkRational.cooperativeEq       avgt       10   6.011        0.193  ns/op
[info] s.b.j.CooperativeEqBenchmarkRational.cooperativeEqInt    avgt       10   8.904        0.207  ns/op
[info] s.b.j.CooperativeEqBenchmarkRational.eqeq                avgt       10   5.852        0.085  ns/op
[info] s.b.j.CooperativeEqBenchmarkRational.eqeqInt             avgt       10  59.530        1.459  ns/op
[info] s.b.j.CooperativeEqBenchmarkRational.eqeqeq              avgt       10   5.509        0.136  ns/op
[info] s.b.j.CooperativeEqBenchmarkRational.equals              avgt       10   2.134        0.065  ns/op
[info] s.b.j.CooperativeEqBenchmarkString.eqeq                  avgt       10   8.343        0.197  ns/op
[info] s.b.j.CooperativeEqBenchmarkString.equal                 avgt       10   3.825        0.184  ns/op
```

**Comment by rklaehn** [comment]
Here are some benchmarks of a version of === that only works if lhs and rhs are of exactly the same type, so e.g. 1 === 1L does not compile. First time I wrote a macro.

https://github.com/rklaehn/spire/commit/015f065418ae4f5c2696364767fa14cbbdfe4787
```
[info] Benchmark                                         Mode  Samples  Score  Score error  Units
[info] s.b.j.LongEqualityCheckBenchmark.compare          avgt       10  2.685        0.052  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.eqeq             avgt       10  0.800        0.005  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.eqeqeq           avgt       10  1.349        0.085  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.strictEq         avgt       10  2.999        0.145  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.strictEqMacro    avgt       10  1.059        0.013  ns/op
```

**Comment by rklaehn** [comment]
OK, so here is a plan for equality. I would love to get some feedback on this from @non or @tixxit. I think replacing the giant match statements in spire with a mechanism like below would be a huge win.

# General #

Equality should be symmetric. `a op b` should have the same result as `b op a`. Also, if `a op b` compiles, so should `b op a`. This is currently not the case for === and =!=

```scala
scala> import spire.implicits._
import spire.implicits._

scala> 1L === 1
res0: Boolean = true

scala> 1 === 1L
<console>:14: error: type mismatch;
 found   : Long(1L)
 required: Int
       1 === 1L
             ^
```

# Strict equality

There should be *some* operator for really strict equality testing. If I write a === b, *I don't want to know if there is a (potentially expensive) implicit conversion in scope that can convert a to the type of b or vice versa.* ***I want this to only compile if the type of a is the same as the type of b*** . This is the operator that I would use most of the time.

As shown from the benchmarks, it is possible to get this behaviour and to also make it as fast as the current === syntax for Eq. Obviously, if you require the same type for lhs and rhs, it is also automatically symmetric.

Ignoring concerns of backwards compatibility, I think it would be best to redefine ===/=!= with the above behaviour. *Can* we ignore backwards compatibility? No idea. But having *another* equality operator ==== or whatever would be really annoying.

# Cooperative equality

This would be used for the various cooperative comparison rules in spire, as well as e.g. for comparing a SortedSet[T] with a HashSet[T] in a modern typeclass-based collection library.

It should also be symmetric.

Cooperative/loose equality should be *as fast as strict equality* for the case that both arguments are of the same type. It should also be possible to define custom cooperative equality between types. E.g. comparing a rational with an int can be made faster than first converting the int to a rational and then comparing.

If lhs and rhs are not of the same type, and there is no exactly matching typeclass, implicit conversions should be used. Usually you only have implicit conversions from "smaller" to "larger" types, e.g. from Int to Long but not vice versa. So I don't think this will cause ambiguities.

I think that a slight performance degradation could be accepted for cooperative equality in the case that you need to use an implicit conversion. If you want full performance, there is always strict equality.

# Test implementation 

The strict equality operator is called ==== to not collide with spires builtin === for now. The cooperative equality operator is called =~= for now.

Strict equality:
```scala
scala> import spire.implicits._
scala> import spire.syntax.strictEq._
scala> 1 ==== 1
res0: Boolean = true

scala> 1 ==== 1L
<console>:17: error: Cannot prove that Int =:= Long.
       1 ==== 1L
         ^

scala> 1L ==== 1
<console>:17: error: Cannot prove that Long =:= Int.
       1L ==== 1
```

Cooperative equality:
```
scala> import spire.math._
scala> import spire.implicits._
scala> import spire.syntax.cooperativeEq._

scala> 1 =~= 1
res0: Boolean = true // compiles because there is an Eq[Int] in scope

scala> 1L =~= 1
res1: Boolean = true // compiles because there is an Eq[Long] and an Int => Long in scope

scala> 1 =~= 1L
res2: Boolean = true // compiles because there is an Eq[Long] and an Int => Long in scope

scala> Rational(1) =~= 1
res3: Boolean = true // compiles because there is an Eq[Rational] and an Int => Rational in scope

scala> 1 =~= "Foo" // does not compile. The error message could be improved though.
<console>:20: error: diverging implicit expansion for type spire.algebra.CooperativeEq[Int,String]
starting with method convertRHS in object CooperativeEq
       1 =~= "Foo"
         ^
```

**Comment by rklaehn** [comment]
Slides from @bvenners that contain some interesting ideas regarding cooperative equality
http://www.slideshare.net/bvenners/equality-for-all

**Comment by non** [comment]
One thing that would be interesting to do here is profile a custom case class (e.g. a `Long` wrapper) that has a `===` method defined on it that only accepts its own type.

```scala
case class Wrapper(n: Long) { lhs =>
  def ===(rhs: Wrapper): Boolean = lhs.n == rhs.n
}
```

Recently @kevinmeredith has been working on ensuring that our concrete number types have type-safe `===` and `=!=` methods and I'd like to put those into the benchmark too.

**Comment by rklaehn** [comment]
I don't think it is possible to disable coercions in that case:

```scala
scala> implicit class LongWrapper(val x: Long) extends AnyVal { lhs => def =+=(rhs: LongWrapper): Boolean = lhs.x == rhs.x }
defined class LongWrapper

scala> 1L =+= 1L
res12: Boolean = true

scala> 1L =+= 1
res13: Boolean = true

scala> 1 =+= 1L
res14: Boolean = true

scala> 1 =+= "Foo"
<console>:25: error: type mismatch;
 found   : String("Foo")
 required: LongWrapper
       1 =+= "Foo"
             ^
```

**Comment by rklaehn** [comment]
Here are benchmark results with the added wrapper approach. Different machine, so slightly different absolute numbers than the previous run.

```
[info] Benchmark                                         Mode  Samples  Score  Score error  Units
[info] s.b.j.LongEqualityCheckBenchmark.compare          avgt       10  3.330        0.238  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.eqeq             avgt       10  0.968        0.034  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.eqeqeq           avgt       10  1.123        0.030  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.strictEq         avgt       10  3.203        0.062  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.strictEqMacro    avgt       10  1.133        0.029  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.wrapperEq        avgt       10  0.961        0.016  ns/op
```

**Comment by non** [comment]
To be clear, I meant `Wrapper` to be a non-primitive, non-value-class. I was really interested in profiling how all of this works for a type like `Rational`, `SafeLong`, etc.

**Comment by rklaehn** [comment]
Strangely enough, it makes no difference whatsoever if I make the LongWrapper a normal case class. It might be that in this case the elusive escape analysis and scalar replacement of the JVM actually does work for a change.

```
[info] Benchmark                                         Mode  Samples  Score  Score error  Units
[info] s.b.j.LongEqualityCheckBenchmark.compare          avgt       10  3.287        0.137  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.eqeq             avgt       10  0.967        0.059  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.eqeqeq           avgt       10  1.093        0.065  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.strictEq         avgt       10  3.033        0.058  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.strictEqMacro    avgt       10  1.064        0.022  ns/op
[info] s.b.j.LongEqualityCheckBenchmark.wrapperEq        avgt       10  0.911        0.028  ns/op
```

**Comment by rklaehn** [comment]
Thinking about this some more, I think the best way to implement the =~= operator would be to do it all with a macro. That way you could easily get full speed for the case where you can use an Eq instance, and you could provide better error messages in case there is a typeclass lookup failure.

**Comment by rklaehn** [comment]
Here are some new benchmarks for the cooperative equaltiy. This is with a macro that finds an Eq instance if lhs and rhs are of the same type. 

So the case where you have an exactly matching CooperativeEq[A, B] is fast. The case where A is B is also fast due to the macro. The case that uses implicit conversions is a bit slower, but acceptable, given that you always have the option to use the non-cooperative equals.

```
[info] Benchmark                                                        Mode  Samples  Score  Score error  Units
[info] s.b.j.LongCooperativeEqualityCheckBenchmark.eqtildeeqFooBar      avgt       10  1.324        0.024  ns/op
[info] s.b.j.LongCooperativeEqualityCheckBenchmark.eqtildeeqIntLong     avgt       10  4.295        0.083  ns/op
[info] s.b.j.LongCooperativeEqualityCheckBenchmark.eqtildeeqLongInt     avgt       10  4.518        0.621  ns/op
[info] s.b.j.LongCooperativeEqualityCheckBenchmark.eqtildeeqLongLong    avgt       10  1.063        0.019  ns/op
```

**Comment by denisrosset** [comment]
Regrouped.
