### ISSUE TITLE
Explicit Syntax for lifting number literals into spire

### ISSUE THREAD

**Issue by JackSullivan** [non/spire#512]
I've noticed that spire can be a bit rough around the edges when it comes to mixing primitive number literals with spire types. I think it would be worthwhile to add an explicit syntax for bring literals into spire. Concretely:
```scala
def foo[N : Field : Trig : NRoot] = {
  val n = (3.5).as[N]
}
```
This would make it clearer which spire methods are dispatching against primitive types, and make it possible to operate with fewer implicits.

**Comment by non** [comment]
:+1:

This syntax should probably live with the other syntax for literal values, and could look something like this:

```scala
implicit class IntAs(val n: Int) extends AnyVal {
  def as[A](implicit ev: Ring[A]): A = ev.fromInt(n)
}
```

(For `Double` literals, we'd want to use `Field[A].fromDouble`.)

**Comment by non** [comment]
If we wanted to get really fancy we could make these into macros to reduce the overhead when literal values are used (especially for zero and one).
