### ISSUE TITLE
Obviate common via package object aliases

### ISSUE THREAD

**Issue by non** [non/spire#529]
On Gitter, @paulp points out that we could remove the need for many of our imports with some aliases in our package objects:

> @non Is there some benefit you obtain from 62 instances of import scala.annotation.tailrec vs. one package object alias of type tailrec = scala.annotation.tailrec ? Similarly for import scala.{specialized => sp} which is a better example because it's inconsistent:
>  20 import scala.{ specialized => spec }
>  57 import scala.{specialized => spec}
>  17 import scala.{specialized => sp}

Let's look into this to help clean up our code.

**Comment by paulp** [comment]
I'll do this.

**Comment by paulp** [comment]
#530
