### ISSUE TITLE
Clarification on AdditiveSemigroup's sumn

### ISSUE THREAD

**Issue by malcolmgreaves** [non/spire#531]
Should `sumn(a, 0)` evaluate to `0` or should it be a runtime exception? 

Thinking about it a bit, it seems to me that it should be `0`. The result of `a added to itself 0 times` is `0`. I noticed that the implementation  [1] throws an exception if the input `n` is `<= 0`. However, the error message is contradictory: it says that `n` must not be `< 0`.

[1] https://github.com/non/spire/blob/master/core/shared/src/main/scala/spire/algebra/Additive.scala#L52

**Comment by tixxit** [comment]
Ah, but `AdditiveSemigroup` doesn't know what 0 is! We must have at least an `AdditiveMonoid` to be able to return 0.

**Comment by denisrosset** [comment]
Yep, you can have a look at `AdditiveMonoid`, which overloads `sumn` with different preconditions.

**Comment by malcolmgreaves** [comment]
Ah ha! I see that clearly now. Thank you both for the clarification!
