### ISSUE TITLE
Add simple combinators to transform Ring, Eq, Group, etc

### ISSUE THREAD

**Issue by tixxit** [non/spire#532]
We should add some simple combinators, like `imap` to `Ring` and `contramap` to `Eq` to change the type.

**Comment by kevinmeredith** [comment]
Could you please state the function signatures of `Ring#imap` and `Eq#contramap`, Tom?

**Comment by tixxit** [comment]
So, for `Ring[A]`, we need 2 functions - one from `A => B`, for converting the results from `Ring[A]` to `B`s and another `B => A`, for converting input arguments to a type compatible with `Ring[A]`. So, for example,

```scala
trait Ring[A] ... {
  ...
  def imap(f: A => B, g: B => A): Ring[B]
  ...
}
```

For `Eq`, we only need a function `B => A` to get an `Eq[B]` from an `Eq[A]`.

**Comment by denisrosset** [comment]
This looks like homomorphisms #627 !
