### ISSUE TITLE
Interval.isBounded seems backwards

### ISSUE THREAD

**Issue by denisrosset** [non/spire#542]
On the typelevel mailing list:

Hello!

I have found that the method isBounded in the spire.math.Interval type works weird:

``` scala
def printIntervalBounded[T](i: Interval[T]) = println(s"$i.isBounded == ${i.isBounded}")


printIntervalBounded(Interval.empty[Long])
printIntervalBounded(Interval("(1,2)"))
printIntervalBounded(Interval("[1,∞)"))
printIntervalBounded(Interval("(-∞,1]"))
printIntervalBounded(Interval.all[Long])
```

gives

``` scala
    (Ø).isBounded == false
    (1, 2).isBounded == false
    [1, ∞).isBounded == true
    (-∞, 1].isBounded == true
    (-∞, ∞).isBounded == true
```

Looks like it returns false for a bounded interval and true for unbounded but it should be the other way around.
It is more obvious if you look at the implementation (https://github.com/non/spire/blob/master/core/shared/src/main/scala/spire/math/Interval.scala):

``` scala
  def isBounded: Boolean =
    this match {
      case Below(_, _) | Above(_, _) | All() => true
      case _ => false
    }
```

Is it a bug or I am missing something?

**Comment by non** [comment]
I think this should be named `isUnbounded`. I agree the logic seems reversed.

**Comment by denisrosset** [comment]
Is corrected now.
