### ISSUE TITLE
"Impure" usage of VectorSpace, Ring...

### ISSUE THREAD

**Issue by denisrosset** [non/spire#544]
I'm writing a linear algebra library using spire. In comparison with breeze, the focus is on exact arithmetic, for example using rationals or cyclotomics.

Already with vectors of a given size, there is the difficulty of writing `VectorSpace` and `Eq` instances. It seems the alternatives are:

1. your vectors have a size known at compile-time, and you use dependent typing trickery,
2. you define your vectors as a `Map[Int, A]`, storing only nonzero elements, losing the length information,
3. you have vectors with a size known at runtime, and you throw when adding vectors of different sizes. Then the ring laws do not hold anymore.

Option 1. works only in special cases such as 3D graphics/games. 

Option 2. seems to work until you arrive at matrix rings, which should have identity elements, and these identity elements depend on the size. This can be seen from the trace of an identity matrix, which is equal to its size.

What should be done about option 3? Should I define variants of the Ring, VectorSpace, ... typeclasses? How should the corresponding laws be modified?

... and should all of this concern Spire at all? Of course, I'm basing my library on Spire for the syntax and the base fields, but these extensions could go in my library. I just want to raise the concern that full purity should not be enforced at the spire/algebra level, but left as a question to user libraries (for example, regarding the laws to enforce).

**Comment by rklaehn** [comment]
1: Do you need to perform calculations on the size, or is it enough to ensure at type level that vectors of non-equal size can not be combined? For the latter, there might be a solution that also works for large N. See http://stackoverflow.com/questions/21296099/limits-of-nat-type-in-shapeless

3: Why exactly do the ring laws not hold anymore? Would it be OK to have an arbitrary that just produces vectors/matrices of the right n?

**Comment by denisrosset** [comment]
@rklaehn 

1. Users will need to perform calculations on the size, for example when concatenating vectors, or appending a row/column of ones to a matrix describing an affine transform in a n-dimensional space.

Let's consider also runtime operations like `nullSpace` whose return matrix size is only known at runtime.

2. The problem is with the laws that check the zero/one elements, who need to have a definite size.

**Comment by denisrosset** [comment]
I solved my problem by using breeze, with all its impurities and ad-hoc type classes.
