### ISSUE TITLE
"Fields are euclidean rings" and the lawless % operator

### ISSUE THREAD

**Issue by denisrosset** [non/spire#568]
I realized that the inclusion "every field is an Euclidean domain" means that all methods on `EuclideanRing` should have default implementations to satisfy the yet-to-be-tested algebraic laws on these structures.

I'm not an expert in ring structures and the introductory (e.g. Wikipedia) leave me somewhat unsatisfied.

I'm opening this issue to do a bit of brainstorming and clean-up. After discussion, I'll propose a PR incorporating the definition and tests.

Every field is an Euclidean domain, and as `x/y` can be computed for any `y!=0`, `mod` is always equal to 0. See discussion [here](http://math.stackexchange.com/questions/1691254/how-to-show-every-field-is-a-euclidean-domain), mathematical definition [here](https://en.wikipedia.org/wiki/Euclidean_domain), also [discussion here](http://math.stackexchange.com/questions/246049/how-do-i-prove-whether-something-is-a-euclidean-domain).

Thus the implementations of `mod`, `quot` and `quotmod` become trivial.

Now, I could not find resources on how to define `gcd` and `lcm`. What I know:
- there is a universal construction for all fields, as the inclusion shows. This inclusion can use all properties of fields, including the existence of a unit for multiplication, and the fact that all non-zero elements have a multiplicative inverse.
- we cannot assume the existence of an order, because the same construction should apply to non-ordered fields such as the complex numbers.

I would be tempted to define `gcd(x,y) = 1`  and `lcm(x,y) = x * y` to satisfy the axioms of [GCD domains](https://en.wikipedia.org/wiki/GCD_domain).

Problem: this clashes with the usual definition of the `%` for doubles, which is inspired by a generalization of the property "how many times this quantity fits in that quantity" on floating point numbers.

I'm not sure what's the best way to proceed here. If we come to the conclusion that `def mod(x: Double, y: Double) = 0.0` is the only construction that obey the GCD domain laws, then the result is going to be quite confusing for users.

On the other hand, `EuclideanRing` does not have any laws yet, which should be corrected.

**Comment by denisrosset** [comment]
Oh, and as a bonus: the value of the program below:

```scala
EuclideanRing.mod(2.0, 4.0) should ===(0.0)
EuclideanRing.mod(2, 4) should ===(2)
```

**Comment by denisrosset** [comment]
OK, in a field, we can define `gcd(x, y)` to be whatever we want. In general, the GCD is not unique. Actually, it's a convention that `gcd(x, y)` is positive for positive integers `x`, `y`.

**Comment by non** [comment]
Right -- the way I've heard this described is that there is more than one valid euclidean for a field, so you can have several different valid mod/gcd/lcm implementations. I think the important thing is that we are consistent.

I'm fine with having fields default to the simple gcd/lcm/mod definitions you proposed, but letting instances (e.g. `Field[Double]`) override them as necessary.

**Comment by denisrosset** [comment]
Agree with you, for `gcd` it's fine to have `Field[Double]` override it. But `mod(x: Double, y: Double)` has to be equal to zero, otherwise laws will fail. For example "mod(x, y) = 0 if y divides x`, which is always true in a field.

**Comment by denisrosset** [comment]
Actually, there is motivation for **two** modulo operators, with a `%` operator that would respect the JVM semantics for the common types (`BigInt`, primitives...), and a `mod` that would obey the ring laws (to be defined). 

See the following:
```scala
scala> BigInt(-2) % 3
res7: scala.math.BigInt = -2

scala> EuclideanRing[BigInt].mod(-2, 3)
res8: BigInt = -2
```

**Comment by denisrosset** [comment]
Indeed, there is motivation for **two** modulo operators. One named `remainder` with a `%` syntax, obeying the currently wide-spread `%` behavior, the other being `mod` obeying the rules of the EuclideanRing under consideration.

In essence, we would follow the `BigInt` semantics, with appropriate generalizations for other primitives.

I'm writing a summary of the situation and will update this issue once done.

**Comment by denisrosset** [comment]
See [work in progress here](https://github.com/denisrosset/algebra/blob/master/EuclidianRing.md)

**Comment by denisrosset** [comment]
See #693

**Comment by denisrosset** [comment]
This is solved now with the `EuclideanRing` and `TruncatedDivision` types.

The operator `%` (and `/~`) are no longer part of spire. Instead, we recommend `emod`, `tmod`, `fmod` and friends.
