### ISSUE TITLE
Interval is not Serializable

### ISSUE THREAD

**Issue by scubamaggo** [non/spire#572]
Interval is not Serializable which leads to its implementing case classes not being Serializable as well. As a minimal example to reproduce use
`abstract class Bar[A: Order]`
 `case class Foo[A: Order](a: A) extends Bar[A]`

which eventually leads to 
`java.io.InvalidClassException: ...$Foo; no valid constructor`
when trying to serialize Foo. Things that would help would be to either have Interval extend Serializable or provide a parameterless constructor manually

**Comment by non** [comment]
Uh oh! Thanks! We'll try to fix this ASAP.

**Comment by non** [comment]
Would you be willing to submit a PR that has `Interval` extend `Serializable` and see if it fixes it for you?

**Comment by non** [comment]
(If that does fix it I'm willing to try to rush a release to fix this. We want all of our data types to be serializable.)

**Comment by scubamaggo** [comment]
Will do

**Comment by scubamaggo** [comment]
It did seem to fix my isses, PR: https://github.com/non/spire/pull/573

**Comment by scubamaggo** [comment]
fixed in https://github.com/non/spire/commit/5d9122db69071545bfceaa73e17da21c1924c979
