### ISSUE TITLE
Suggestions for hacktoberfest PR's?

### ISSUE THREAD

**Issue by RatanRSur** [non/spire#591]
Hi!

I'm doing hacktoberfest and although I could always make 4 documentation changes if it comes to that, I want to do something more substantive and more importantly, ask the community at various repos what they want done. Anything jump to mind?

Thanks!

**Comment by denisrosset** [comment]
Hi @RatanRSur,
I think your question would be more suitable in our gitter channel: https://gitter.im/non/spire
The root-finding algorithm for polynomials seems still to have failures with small probability in the randomized tests. Having those random failures in explicit test cases would help us a lot.
Or adding more randomized tests to stress test the current code!
BTW, thanks for your inquiry; if you don't mind, I'm closing this issue and we can move the discussion to Gitter.
