### ISSUE TITLE
Create release for Scala 2.12

### ISSUE THREAD

**Issue by hohonuuli** [non/spire#596]
Scala 2.12.0 has been published in Maven central. See [http://get-scala.org/2.12](http://get-scala.org/2.12). The team is waiting until important libraries have been published against 2.12 before making a public announcement.

**Comment by hohonuuli** [comment]
Just a note that some of spire's dependencies are not available for 2.12 yet:

```
	::::::::::::::::::::::::::::::::::::::::::::::
 	::          UNRESOLVED DEPENDENCIES         ::
 	::::::::::::::::::::::::::::::::::::::::::::::
	:: org.typelevel#machinist_2.12;0.4.1: not found
	:: org.scalacheck#scalacheck_2.12;1.12.4: not found
 	:: org.scalatest#scalatest_2.12;3.0.0-M7: not found
 	:: com.chuusai#shapeless_2.12;2.2.5: not found
	:: org.scoverage#scalac-scoverage-runtime_2.12;1.1.0: not found
 	:: org.scoverage#scalac-scoverage-plugin_2.12;1.1.0: not found
 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by sarahgerweck** [comment]
I believe most, if not all, of these are now all available for 2.12. Any chance we can get a release here?

**Comment by cchantep** [comment]
:+1

**Comment by xuwei-k** [comment]
> I believe all of these, except perhaps the coverage plugins, are now available for 2.12.

I think so too. start off with https://github.com/non/spire/pull/600

**Comment by rleibman** [comment]
For fun, I used sbt-dependency to update the project to the latest code of everything, to get to 2.12. I get the following errors:
[info] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/optional/mapIntIntPermutation.scala:39: non-literal range
[info]     cforRange(0 until sa.size) { k =>
[info]                                ^
[info] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/optional/mapIntIntPermutation.scala:39: non-literal range
[info]     cforRange(0 until sa.size) { k =>
[info]                                ^
[error] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/std/option.scala:12: value combine is not a member of spire.algebra.Semigroup[A]
[error]     case (Some(x), Some(y)) => Some(x |+| y)
[error]                                       ^
[info] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/optional/mapIntIntPermutation.scala:39: non-literal range
[info]     cforRange(0 until sa.size) { k =>
[info]                                ^
[error] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/std/option.scala:12: value combine is not a member of spire.algebra.Semigroup[A]
[error]     case (Some(x), Some(y)) => Some(x |+| y)
[error]                                       ^
[info] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/optional/mapIntIntPermutation.scala:39: non-literal range
[info]     cforRange(0 until sa.size) { k =>
[info]                                ^
[error] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/syntax/std/Ops.scala:91: too many arguments (2) for method combine: (as: TraversableOnce[A])A
[error]     cfor(0)(_ < arr.length, _ + 1) { i => result |+|= arr(i) }
[error]                                                          ^
[error] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/syntax/std/Ops.scala:91: too many arguments (2) for method combine: (as: TraversableOnce[A])A
[error]     cfor(0)(_ < arr.length, _ + 1) { i => result |+|= arr(i) }
[error]                                                          ^
[error] two errors found
[warn] one warning found
[error] two errors found
[error] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/std/option.scala:12: value combine is not a member of spire.algebra.Semigroup[A]
[error]     case (Some(x), Some(y)) => Some(x |+| y)
[error]                                       ^
[error] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/std/option.scala:12: value combine is not a member of spire.algebra.Semigroup[A]
[error]     case (Some(x), Some(y)) => Some(x |+| y)
[error]                                       ^
[error] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/syntax/std/Ops.scala:91: too many arguments (2) for method combine: (as: TraversableOnce[A])A
[error]     cfor(0)(_ < arr.length, _ + 1) { i => result |+|= arr(i) }
[error]                                                          ^
[error] /home/rleibman/workspace/spire/core/shared/src/main/scala/spire/syntax/std/Ops.scala:91: too many arguments (2) for method combine: (as: TraversableOnce[A])A
[error]     cfor(0)(_ < arr.length, _ + 1) { i => result |+|= arr(i) }
[error]                                                          ^

**Comment by rleibman** [comment]
@xuwei-k I tried to build your 2.12 branch and had some problems in laws:
[error] /home/rleibman/workspace/spire/laws/src/main/scala/spire/laws/VectorSpaceLaws.scala:100: No implicit view available from org.scalacheck.Properties => org.scalacheck.Prop.
[error]     "linearity of partial inner product" → forAll((w: V) =>
[error]                                                  ^
[error] /home/rleibman/workspace/spire/laws/src/main/scala/spire/laws/VectorSpaceLaws.scala:100: No implicit view available from org.scalacheck.Properties => org.scalacheck.Prop.
[error]     "linearity of partial inner product" → forAll((w: V) =>
[error]                                                  ^
[error] /home/rleibman/workspace/spire/laws/src/main/scala/spire/laws/gen.scala:207: value rng is not a member of org.scalacheck.Gen.Parameters
[error]       import params.rng.nextInt
[error]                     ^
[error] /home/rleibman/workspace/spire/laws/src/main/scala/spire/laws/gen.scala:211: not found: value nextInt
[error]         val j = nextInt(i + 1) // uses the Fisher-Yates shuffle, inside out variant
[error]                 ^
[warn] /home/rleibman/workspace/spire/laws/src/main/scala/spire/laws/gen.scala:207: Unused import
[warn]       import params.rng.nextInt
[warn]                         ^
[info] No documentation generated with unsuccessful compiler run
[warn] one warning found
[error] /home/rleibman/workspace/spire/laws/src/main/scala/spire/laws/gen.scala:207: value rng is not a member of org.scalacheck.Gen.Parameters
[error]       import params.rng.nextInt
[error]                     ^
[error] three errors found
[error] /home/rleibman/workspace/spire/laws/src/main/scala/spire/laws/gen.scala:211: not found: value nextInt
[error]         val j = nextInt(i + 1) // uses the Fisher-Yates shuffle, inside out variant
[error]                 ^
[warn] /home/rleibman/workspace/spire/laws/src/main/scala/spire/laws/gen.scala:207: Unused import
[warn]       import params.rng.nextInt
[warn]                         ^
[warn] one warning found

**Comment by SethTisue** [comment]
is anyone working on this?

**Comment by xuwei-k** [comment]
http://repo1.maven.org/maven2/org/spire-math/spire_2.12/0.13.0/

spire 0.13.0 support Scala 2.12

**Comment by SethTisue** [comment]
great! https://github.com/scala/make-release-notes/commit/07f6513ff6c56571b855b2a89fcef633a71e10ee

I will also attempt to re-add Spire to the Scala 2.12 community build.

looks like somebody should update the README in this repo and close this ticket?

**Comment by xuwei-k** [comment]
> looks like somebody should update the README in this repo

https://github.com/non/spire/commit/69cf94c4bab3cf0e1b54b9014b3dbfbed289b23a#diff-04c6e90faac2675aa89e2176d2eec7d8R55

**Comment by denisrosset** [comment]
Done.
