### ISSUE TITLE
Minor typo in User's Guide

### ISSUE THREAD

**Issue by MichaelJAllen** [non/spire#597]
The _User's Guide_ document states the anti-symmetry condition for partial ordering to be:

- if `a <= b` and `b <= a`, then `a === c` (anti-symmetry)

I'm guessing that this should read:

- if `a <= b` and `b <= a`, then `a === b` (anti-symmetry)

BTW, thanks for this fantastic library!

**Comment by non** [comment]
Ah, yes, definitely a typo. Thanks!

**Comment by denisrosset** [comment]
Has been corrected, closing.
