### ISSUE TITLE
Ring got its typeclasses the weird way round?

### ISSUE THREAD

**Issue by fommil** [non/spire#632]
```
Ring[A] types that form a group under + and a monoid under *
```

this is kind of weird, I would have expected the Monoid to be on the `+` and the group to be on `*`

**Comment by denisrosset** [comment]
In a ring, you have `a + b`, `a + 0 = a` and `a + (-a) = 0`. Thus a group (binary operation, neutral element, inverse under the binary operation). Moreover, `+` is commutative.

However, `Ring` only provide `a * b` and `a * 1 = a`, as the division singles out fields.

**Comment by fommil** [comment]
Ah, I see. I think I'm reading the doc slightly wrongly, I thought it was saying that `+` is the ring and `*` is the monoid. This would perhaps have cleared it up for me

```
Ring[A] types of two binary operators: + (abelian group) and * (monoid)
```
