### ISSUE TITLE
Error in Interval.isBounded method

### ISSUE THREAD

**Issue by spockoyno** [non/spire#648]
It appears that the opposite result is produced. For instance, Interval.above(0).isBounded gives "true", 
whereas Interval.closed(0, 5).isBounded gives "false".

**Comment by denisrosset** [comment]
Confirmed on latest master. Will be writing a test case.

**Comment by denisrosset** [comment]
@tixxit @non @rklaehn : it's been such a long time, I forgot to make the change on a PR and pushed directly to master. Please +1 the following two commits:

https://github.com/non/spire/commit/a7b828f904cc34c05bd0dd94c56a1631dece68d2

https://github.com/non/spire/commit/297ee88fd6276f7a69881fecc807c96971f2fe2d

(I will revert if needed).

**Comment by denisrosset** [comment]
Corrected.
