### ISSUE TITLE
Deploy cfor as independant module

### ISSUE THREAD

**Issue by slandelle** [non/spire#650]
Hi there,

The `cfor` macros are great and are actually not really related to the rest of the work in Spire.

Sadly, it's not an independent module, so one only interested in `cfor` has to deploy the full spire library, hence 7.7 MB.

Would it be possible to extract it and deploy it separately?

Regards,

**Comment by denisrosset** [comment]
Hi,
definitely interested in doing so. This module would also include the lightweight option `Opt`.
I'm in the middle of relocating, so feel free to push this forward with a PR, otherwise I'll get back to it in a bit.

**Comment by slandelle** [comment]
Hi,

Great news, thanks a lot!
Sorry, I'm a bit in a rush atm, so I'll try to send a PR next week.

FYI, I had to deploy such extract in a hurry on my side (https://github.com/gatling/gatling-spire). I'll drop it as soon as it's possible.

Thanks again!

**Comment by denisrosset** [comment]
Hi @slandelle, i started the work in #651.

Going to work on the `cfor` macros now.

**Comment by slandelle** [comment]
Hi @denisrosset 

Awesome, thanks a lot!!!

**Comment by denisrosset** [comment]
@slandelle Part of the modularization work undergoing. Closing.

**Comment by slandelle** [comment]
I should have closed myself, sorry (I've already [switched back to spire-macros](https://github.com/gatling/gatling/blob/master/project/Dependencies.scala#L24)).

Thanks a lot!
