### ISSUE TITLE
Complex(0.0, 0.0).norm == NaN

### ISSUE THREAD

**Issue by ryan-williams** [non/spire#661]
I expected a result of `0` here:

```scala
import spire._, math._, implicits._, algebra._
Complex(0.0, 0.0).norm  // NaN
```

[This is the cause in 0.14.1](https://github.com/non/spire/blob/v0.14.1/core/shared/src/main/scala/spire/math/package.scala#L408):

```scala
final def hypot[@sp(Float, Double) A](x: A, y: A)
  (implicit f: Field[A], n: NRoot[A], s: Signed[A]): A = {
  import spire.implicits._
  def abs(n: A): A = if (n < f.zero) -n else n
  if (x > y) abs(x) * (1 + (y/x)**2).sqrt
  else abs(y) * (1 + (x/y)**2).sqrt
}
```

Seems like a convoluted way to do this computation, is there a reason to not just say e.g. `(x*x + y*y).sqrt?

I love this library btw 😍  🙏🏻

**Comment by ryan-williams** [comment]
Looks like `.abs` does what I want:

```scala
scala> Complex(0.0, 0.0).abs
res2: Double = 0.0

scala> Complex(3.0, 4.0).abs
res3: Double = 5.0
```

Not sure if this difference between `abs` and `norm` makes sense / is intentional; feel free to close if so!

**Comment by pleira** [comment]
For your information, the standard approach to calculating the hypotenuse is subject to overflows. The approach here is numerically stable and avoids this problem

**Comment by ryan-williams** [comment]
ah that makes sense, thanks. Do you think it's worth checking for a zero denominator thought?

**Comment by pleira** [comment]
To be in the zero denominator case you need to pass zero to x and a negative value to y. But well, these values do not make sense for the hypotenuse ... I think the client code should do the checks.

**Comment by ryan-williams** [comment]
See the example at the top of this post: `Complex.norm` calls `hypot`, and gives a `NaN` when it probably shouldn't.

You're right that this problem affects all negative real numbers, not just `0`:

```scala
Complex(-1.0).norm
res1: Double = NaN
```

**Comment by ryan-williams** [comment]
It happens for `Complex` numbers with no real component as well:

```scala
Complex(0, -1.0).norm
res2: Double = NaN
```

If this is "working as intended" for `hypot`, then `Complex.norm` shouldn't call `hypot`, is my current feeling.

Is `norm` of a complex number supposed to be semantically different from `abs`?

**Comment by pleira** [comment]
Indeed, in your example, the norm should be one. I see also as a hint that hypot should be patched. I think this kind of check would work:
```scala
if (abs(x) > abs(y)) abs(x) * (1 + (y/x)**2).sqrt
else abs(y) * (1 + (x/y)**2).sqrt
```

**Comment by ryan-williams** [comment]
I think that would still `NaN` when `y` is 0, aka for `Complex`s that represent real numbers

**Comment by pleira** [comment]
Yes, the norm should give 0 instead as you say. A fix could be in the norm method, by doing some checks and not calling hypot.
