### ISSUE TITLE
Infinite loop in BigDecimal.sqrt

### ISSUE THREAD

**Issue by ryan-williams** [non/spire#664]
```scala
import spire.implicits._
BigDecimal("4.000000000000000000000000000000003").sqrt
```

enters an infinite loop [here](https://github.com/non/spire/blob/v0.14.1/core/shared/src/main/scala/spire/std/bigDecimal.scala#L52):

```scala
@tailrec def loop(x: BigDecimal, y: BigDecimal): BigDecimal =
  if (x == y) y else loop(y, ((n / y) + y) / two)
```

with values:

```
x: 2.000000000000000000000000000000001
y: 2.000000000000000000000000000000000
n: 4.000000000000000000000000000000003
```

affects `0.13.0` and `0.14.1`

**Comment by tixxit** [comment]
Oof - thanks for the report. I've had a lot of problems using Scala's default `BigDecimal` for this kind of code. It seems like `NRoot[BigDecimal].nroot(BigDecimal("4.000000000000000000000000000000003", 2)` doesn't have this problem. Worst case we can avoid optimizing for the sqrt case. However, it's likely worth refactoring `sqrt` to use `java.math.BigDecimal` internally instead and being explicit about precision and rounding.

**Comment by ryan-williams** [comment]
gtk! I was about to test a fix that just detects the infinite case (looking at it again, I'm guessing it is repeating with period 2, i.e. `x` and `y` are just swapped at each iteration?) and breaks out, which will at least unblock me for now.
