### ISSUE TITLE
Polynomial constructors should collapse additive-inverse terms

### ISSUE THREAD

**Issue by ryan-williams** [non/spire#670]
```scala
import spire._, math._, poly._
val t = Term(Rational(8, 7), 1)  // 8x/7
val p = Polynomial(Seq(t, -t))
// p: spire.math.poly.PolySparse[spire.math.Rational] = ()

p.isZero  // false; bad!
val p2 = p.toDense.toSparse  // (0)
p2.isZero  // true
p2 == p  // false; bad!
```

`Polynomial.apply` and `PolySparse.apply` will happily generate ~invalid polynomials this way.

This means `PolynomialCheck` has had several broken tests (which fail nondeterministically, cf #665, which failed 2 of 3 jobs in a recent CI on #668).

I'll look into fixing it as well as otherwise working-around the tests' issue.

**Comment by ryan-williams** [comment]
#669 also [just failed due to this](https://travis-ci.org/non/spire/jobs/342098503)

**Comment by denisrosset** [comment]
@ryan-williams (Still doing clean up) Do you think this is still a bug?

**Comment by ryan-williams** [comment]
Thanks @denisrosset, I think https://github.com/non/spire/pull/653 fixed this!
